import Banner from "./Banner/Banner";
import Nav from "./Nav";
import AdminNavbar from "./AdminNavbar/AdminNavbar";
// import Services from "./Services";
// import Work from "./Work";
import Header from "./Header/Header";
// import Customer from "./Customer/Customer";
// import Provider from "./Provider";
import HeaderToggle from "./HeaderToggle/HeaderToggle";
// import  Categories  from "./Categories/Categories";
// import  CategoriesCard  from "./CategoriesCard/CategoriesCard";
import Vendor from "./Vendor/Vendor";
import VendorCard from "./VendorCard/VendorCard";
import ChooseUs from "./ChooseUs/ChooseUs";
import IconNdText from "./IconNdText/IconNdText";
import Testimonial from "./Testimonial/Testimonial";
import TestimonialCard from "./TestimonialCard/TestimonialCard";
import Statics from "./Statics/Statics";
// import Jobs from "./Jobs/Jobs";
// import JobCard from "./JobCard/JobCard";
import Footer from "./Footer/Footer";
import Borrowed from "./Borrowed/Borrowed";
import Sidebar from "./Sidebar/Sidebar";
import UserNavbar from "./UserNavbar/UserNavbar";
// import ServiceProvider from "./ServiceProvider/ServiceProvider";
// import Filter from "./Filter/Filter";
// import TimeSlot from "./TimeSlot/TimeSlot";
// import ServiceCard from "./ServiceCard/ServiceCard";
// import CustomerBookingDetail from "./CustomerBookingDetail/CustomerBookingDetail";
// import ConfirmPage from "./ConfirmPage/ConfirmPage";
// export {Banner,TimeSlot,AdminNavbar,ConfirmPage,Filter,CustomerBookingDetail,Footer,ServiceCard,ServiceProvider,Statics,Nav,Testimonial,Jobs,JobCard,TestimonialCard,IconNdText,Services,Work,Header,Customer,Provider,HeaderToggle,Categories,CategoriesCard,Vendor,VendorCard,ChooseUs};
export {Banner,Borrowed,UserNavbar,Nav,Sidebar,AdminNavbar,Header,HeaderToggle,Vendor,VendorCard,ChooseUs,Testimonial,TestimonialCard,Statics,Footer,IconNdText}